### ISSUE TITLE
Flow stopped working, when activating plugin

### ISSUE THREAD

**Issue by Flippo24** [retejs/profiler-plugin#1]
When enable the ProfilerPlugin the flow stopped working. Used in the module example.

![grafik](https://user-images.githubusercontent.com/5230426/41715412-a98bd1be-7553-11e8-8b5b-eac60b602556.png)

When plugin is diabled flow works normal.

**Comment by Ni55aN** [comment]
In which order are the plugins used?

**Comment by Flippo24** [comment]
In index.js ...

`...
var editor = new Rete.NodeEditor("demo@0.1.0", container);
editor.use(ConnectionPlugin, { curvature: 0.4 });
editor.use(AlightRenderPlugin);
editor.use(ContextMenuPlugin);

var engine = new Rete.Engine("demo@0.1.0");
editor.use(ModulePlugin, { engine, modules });
**engine.use(ProfilerPlugin, { editor, enabled: true });**
...`

**Comment by Ni55aN** [comment]
I figured out the problem and fixed it.
Please update profiler to v0.1.3

https://codepen.io/Ni55aN/pen/QOEbEW?editors=0010 (uncomment `.use(ProfilerPlugin`)

**Comment by Flippo24** [comment]
Works like a charm. Thank you.
