### ISSUE TITLE
Compatibility with "module-plugin"

### ISSUE THREAD

**Issue by Sarps** [retejs/profiler-plugin#4]
The plugin doesn't seem to be compatible with the module-plugin. Whenever I offload and load a new module, I lose all the profile data on the previous. Plus the loaded module doesn't seem to be profiled as well.

**Comment by Ni55aN** [comment]
Module plugin is deprecated. I'm not sure if it makes sense to reimplement the current plugin for v2 (rather it will be as a set of practices and examples), but I do not recommend using them for v1 of the framework

**Comment by Sarps** [comment]
What would you recommend I use as a replacement for the module plugin. I need a way to group and collapse nodes from the view so it's not all cluttered

**Comment by Ni55aN** [comment]
I would recommend to use v2 and refer to [Modules guide](https://retejs.org/docs/guides/modules) (but be prepared for some breaking changes in the coming month)

**Comment by Sarps** [comment]
Sure, I'll consider that. Thanks.
